### ISSUE TITLE
Need to finish adding footers 

### ISSUE THREAD

**Issue by rommeltrejo** [goldenromeo/Project2#2]
.

**Comment by rommeltrejo** [comment]
think I finished fixing the footer positions

**Comment by nomadicdog** [comment]
kk Im going to add my part tonight to finish this off.

**Comment by up85972** [comment]
Just be careful, I think one of the automatic pushes broke a few pages. I fixed the ones I found but there might be more.

**Comment by nomadicdog** [comment]
mmk.

**Comment by rommeltrejo** [comment]
admin side is clear

**Comment by rommeltrejo** [comment]
User side is clear . Last thing I will update is the footer.html links but that will not interfere with anything else.
